Feature > Request Geocode
KindyNowApp/ex_geocode pull request #1
Opened 2016-10-14 01:10 UTC by sinakarimi

2016-10-17 00:30 UTC, sinakarimi commented
![](https://github.trello.services/images/mini-trello-icon.png) [[CC] Geocode Library](https://trello.com/c/TnjayuNg/31-cc-geocode-library)

2016-10-19 13:29 UTC, craigp requested changes
Aside from the config issue I ran into everything else was working fine 👍

2016-10-19 13:29 UTC, craigp commented on config/config.exs
> +  api_host: "https://maps.googleapis.com/maps/api/geocode"
I had to edit the `api_host` to remove the path in order to get this to work, ie. `api_host: https://maps.googleapis.com`

2016-11-01 14:30 UTC, craigp approved these changes

2016-11-01 14:32 UTC, craigp commented
Hope you don't mind me committing to this, I was just catching up on PR's I needed to review and thought I'd help out.

2016-11-07 18:08 UTC, craigp commented
Are you happy to merge this in?

2016-12-22 03:50 UTC, merged